apiVersion: v1
kind: Service
metadata:
apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    name: html-nodeport-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30000
  selector:
    app: html
